#!/bin/bash -e

ldconfig

if [ -x "$(command -v update-rc.d)" ]; then
	update-rc.d testo-nn-server defaults
fi

if [ -x "$(command -v chkconfig)" ]; then
	chkconfig testo-nn-server on
fi

service testo-nn-server start
