#!/bin/bash -e

service testo-nn-server stop

if [ -x "$(command -v update-rc.d)" ]; then
	update-rc.d testo-nn-server remove
fi

if [ -x "$(command -v chkconfig)" ]; then
	chkconfig testo-nn-server off
fi
