#!/bin/bash
#
### BEGIN INIT INFO
# Provides: negotiator-agent
# Required-Start: $local_fs $remote_fs $syslog
# Required-Stop: $local_fs $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: negotiator-agent
# Description: negotiator-agent
### END INIT INFO
#

case "$1" in
	start)
		daemon --name negotiator-agent --unsafe -- negotiator-agent
		;;

	stop)
		daemon --name --negotiator-agent --stop
		;;

	restart)
		daemon --name --negotiator-agent --restart
		;;

	status)
		daemon --name --negotiator-agent --running
		;;

	*)
		echo "Usage: /etc/init.d/negotiator-agent {start|stop|restart|status}"
		exit 1
		;;
esac

exit $?
