#!/bin/bash -e

if [ -x "$(command -v update-rc.d)" ]; then
	update-rc.d testo-guest-additions defaults
fi

if [ -x "$(command -v chkconfig)" ]; then
	chkconfig testo-guest-additions on
fi

service testo-guest-additions start
