#!/bin/bash
#
### BEGIN INIT INFO
# Provides: negotiator-agent
# Required-Start: $local_fs $remote_fs $syslog
# Required-Stop: $local_fs $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: testo-guest-additions
# Description: testo-guest-additions
### END INIT INFO
#

case "$1" in
	start)
		daemon --name testo-guest-additions --unsafe -- testo-guest-additions
		;;

	stop)
		daemon --name --testo-guest-additions --stop
		;;

	restart)
		daemon --name --testo-guest-additions --restart
		;;

	status)
		daemon --name --testo-guest-additions --running
		;;

	*)
		echo "Usage: /etc/init.d/testo-guest-additions {start|stop|restart|status}"
		exit 1
		;;
esac

exit $?
